"""
This type stub file was generated by pyright.
"""

class StatsRecorder:
    def __init__(self, directory, file_prefix, autoreset=..., env_id=...) -> None:
        ...
    
    @property
    def type(self): # -> str:
        ...
    
    @type.setter
    def type(self, type): # -> None:
        ...
    
    def before_step(self, action): # -> None:
        ...
    
    def after_step(self, observation, reward, done, info): # -> None:
        ...
    
    def before_reset(self): # -> None:
        ...
    
    def after_reset(self, observation): # -> None:
        ...
    
    def save_complete(self): # -> None:
        ...
    
    def close(self): # -> None:
        ...
    
    def flush(self): # -> None:
        ...
    


