language: python
python:
  - "3.9"

branches:
  only:
    - main
    - CI-Travis

stages:
  - lint
  - test

cache:
  pip: true

jobs:
  include:
    - stage: lint
      install:
        - pip install --upgrade pip
        - pip install poetry
        - poetry install -v
      script:
        - codespell || true  # --ignore-words-list="" --skip=""
        - mypy --install-types --non-interactive --exclude docs/ .
        - black --check --diff --color .
        - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --show-source --statistics
        - isort --check-only --profile black .
    - stage: test
      install:
        - pip install --upgrade pip
        - pip install poetry
        - poetry install -v
      script:
        - pytest
        - pytest --doctest-modules .
        - shopt -s globstar && pyupgrade --py39-plus **/*.py || true
