language: python
python:
  - "3.9"

branches:
only:
  - main

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - pytest


jobs:
  include:
    - stage: lint
      script:
        - 

    - stage: test
      script: 
        - run: pip install pytest pyupgrade
        - run: pip install -r requirements.txt
        - run: pytest . || true
        - run: pytest --doctest-modules . || true
        - run: shopt -s globstar && pyupgrade --py39-plus **/*.py || true
