"""
This type stub file was generated by pyright.
"""

from gym import ObservationWrapper

class FlattenObservation(ObservationWrapper):
    r"""Observation wrapper that flattens the observation."""
    def __init__(self, env) -> None: ...
    def observation(self, observation): ...
