"""
This type stub file was generated by pyright.
"""

import gym
from typing import Callable

def capped_cubic_video_schedule(episode_id):
    ...

class RecordVideo(gym.Wrapper):
    def __init__(self, env, video_folder: str, episode_trigger: Callable[[int], bool] = ..., step_trigger: Callable[[int], bool] = ..., video_length: int = ..., name_prefix: str = ...) -> None:
        ...
    
    def reset(self, **kwargs):
        ...
    
    def start_video_recorder(self): # -> None:
        ...
    
    def step(self, action):
        ...
    
    def close_video_recorder(self) -> None:
        ...
    


