"""
This type stub file was generated by pyright.
"""

import gym

class RecordEpisodeStatistics(gym.Wrapper):
    def __init__(self, env, deque_size=...) -> None: ...
    def reset(self, **kwargs): ...
    def step(self, action): ...
