"""
This type stub file was generated by pyright.
"""

"""A set of common utilities used within the environments. These are
not intended as API functions, and will not remain stable over time.
"""
color2num = ...

def colorize(string, color, bold=..., highlight=...):  # -> str:
    """Return string surrounded by appropriate terminal color codes to
    print colorized text.  Valid colors: gray, red, green, yellow,
    blue, magenta, cyan, white, crimson
    """
    ...
