"""
This type stub file was generated by pyright.
"""

class EzPickle:
    """Objects that are pickled and unpickled via their constructor
    arguments.

    Example usage:

        class Dog(Animal, EzPickle):
            def __init__(self, furcolor, tailkind="bushy"):
                Animal.__init__()
                EzPickle.__init__(furcolor, tailkind)
                ...

    When this object is unpickled, a new Dog will be constructed by passing the provided
    furcolor and tailkind into the constructor. However, philosophers are still not sure
    whether it is still the same dog.

    This is generally needed only for environments which wrap C/C++ code, such as MuJoCo
    and Atari.
    """
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def __getstate__(self): # -> dict[str, tuple[Unknown, ...] | dict[str, Unknown]]:
        ...
    
    def __setstate__(self, d): # -> None:
        ...
    


