"""
This type stub file was generated by pyright.
"""

from .base import BaseWrapper

class AssertOutOfBoundsWrapper(BaseWrapper):
    '''
    this wrapper crashes for out of bounds actions
    Should be used for Discrete spaces
    '''
    def __init__(self, env) -> None:
        ...
    
    def step(self, action): # -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


