"""
This type stub file was generated by pyright.
"""

from pettingzoo.utils.env import AECEnv

class BaseWrapper(AECEnv):
    '''
    Creates a wrapper around `env` parameter. Extend this class
    to create a useful wrapper.
    '''
    def __init__(self, env) -> None:
        ...
    
    @property
    def observation_spaces(self): # -> dict[Unknown, Unknown]:
        ...
    
    @property
    def action_spaces(self): # -> dict[Unknown, Unknown]:
        ...
    
    def observation_space(self, agent):
        ...
    
    def action_space(self, agent):
        ...
    
    @property
    def unwrapped(self):
        ...
    
    def seed(self, seed=...): # -> None:
        ...
    
    def close(self): # -> None:
        ...
    
    def render(self, mode=...):
        ...
    
    def reset(self): # -> None:
        ...
    
    def observe(self, agent):
        ...
    
    def state(self):
        ...
    
    def step(self, action): # -> None:
        ...
    
    def __str__(self) -> str:
        '''
        returns a name which looks like: "max_observation<space_invaders_v1>"
        '''
        ...
    


