"""
This type stub file was generated by pyright.
"""

from .base import BaseWrapper

class CaptureStdoutWrapper(BaseWrapper):
    def __init__(self, env) -> None: ...
    def render(self, mode=...): ...
    def __str__(self) -> str: ...
