"""
This type stub file was generated by pyright.
"""

from .base import BaseWrapper

class ClipOutOfBoundsWrapper(BaseWrapper):
    """
    this wrapper crops out of bounds actions for Box spaces
    """

    def __init__(self, env) -> None: ...
    def step(self, action): ...
    def __str__(self) -> str: ...
