"""
This type stub file was generated by pyright.
"""

from .base import BaseWrapper

class TerminateIllegalWrapper(BaseWrapper):
    """
    this wrapper terminates the game with the current player losing
    in case of illegal values

    parameters:
        - illegal_reward: number that is the value of the player making an illegal move.
    """

    def __init__(self, env, illegal_reward) -> None: ...
    def reset(self): ...
    def observe(self, agent): ...
    def step(self, action): ...
    def __str__(self) -> str: ...
