"""
This type stub file was generated by pyright.
"""

def average_total_reward(env, max_episodes=..., max_steps=...):
    '''
    Runs an env object with random actions until either max_episodes or
    max_steps is reached. Calculates the average total reward over the
    episodes.

    Reward is summed across all agents, making it unsuited for use in zero-sum
    games.
    '''
    ...

