"""
This type stub file was generated by pyright.
"""

class capture_stdout:
    """
    usage:

    with capture_stdout() as var:
        print("hithere")

        # value of var will be "hithere"
        data = var.getvalue()
    """

    def __init__(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, type, value, traceback): ...
