"""
This type stub file was generated by pyright.
"""

class DeprecatedEnv(ImportError):
    ...


class DeprecatedModule:
    def __init__(self, name, old_version, new_version) -> None:
        ...
    


def is_env(env_name): # -> bool:
    ...

def depricated_handler(env_name, module_path, module_name):
    ...

