"""
This type stub file was generated by pyright.
"""

import logging

class EnvLogger:
    mqueue = ...
    _output = ...
    @staticmethod
    def get_logger(): # -> Logger:
        ...
    
    @staticmethod
    def flush(): # -> None:
        ...
    
    @staticmethod
    def suppress_output(): # -> None:
        ...
    
    @staticmethod
    def unsuppress_output(): # -> None:
        ...
    
    @staticmethod
    def error_possible_agents_attribute_missing(name): # -> NoReturn:
        ...
    
    @staticmethod
    def warn_action_out_of_bound(action, action_space, backup_policy): # -> None:
        ...
    
    @staticmethod
    def warn_close_unrendered_env(): # -> None:
        ...
    
    @staticmethod
    def warn_close_before_reset(): # -> None:
        ...
    
    @staticmethod
    def warn_on_illegal_move(): # -> None:
        ...
    
    @staticmethod
    def error_observe_before_reset(): # -> NoReturn:
        ...
    
    @staticmethod
    def error_step_before_reset(): # -> NoReturn:
        ...
    
    @staticmethod
    def warn_step_after_done(): # -> None:
        ...
    
    @staticmethod
    def error_render_before_reset(): # -> NoReturn:
        ...
    
    @staticmethod
    def error_agent_iter_before_reset(): # -> NoReturn:
        ...
    
    @staticmethod
    def error_nan_action(): # -> NoReturn:
        ...
    
    @staticmethod
    def error_state_before_reset(): # -> NoReturn:
        ...
    


class EnvWarningHandler(logging.Handler):
    def __init__(self, *args, mqueue, **kwargs) -> None:
        ...
    
    def emit(self, record): # -> None:
        ...
    


