"""
This type stub file was generated by pyright.
"""

def hash(val): # -> str:
    ...

def calc_hash(new_env, rand_issue, max_env_iters):
    ...

def seed_action_spaces(env): # -> None:
    ...

def check_environment_deterministic(env1, env2, num_cycles): # -> bool:
    '''
    env1 and env2 should be seeded environments

    returns a bool: true if env1 and env2 execute the same way
    '''
    ...

def hash_obsevation(obs): # -> str | Literal[0]:
    ...

def test_environment_reset_deterministic(env1, num_cycles): # -> None:
    ...

def seed_test(env_constructor, num_cycles=..., test_kept_state=...): # -> None:
    ...

