"""
This type stub file was generated by pyright.
"""

def test_state_space(env): # -> None:
    ...

def test_state(env, num_cycles):
    ...

def test_parallel_env(parallel_env): # -> None:
    ...

def state_test(env, parallel_env, num_cycles=...): # -> None:
    ...

