"""
This type stub file was generated by pyright.
"""

from gym import error, logger, vector, wrappers
from gym.version import VERSION as __version__
from gym.core import ActionWrapper, Env, GoalEnv, ObservationWrapper, RewardWrapper, Wrapper
from gym.spaces import Space
from gym.envs import make, register, spec

__all__ = ["Env", "Space", "Wrapper", "make", "spec", "register"]
